---
- name: Include global variables
  include_vars:
    file: "{{ playbook_dir }}/vars/global.yaml"
  tags: global_vars

- name: Descargar e instalar uv usando el script oficial
  shell: "curl -LsSf {{ sentu_install.install_scripts.uv }} | sh"
  become: false
  register: uv_install_output
  changed_when: "'uv installed successfully' not in uv_install_output.stdout"
  when: sentu_install.install_scripts.uv is defined
  tags: install_uv
