---
- name: Instalar Ruby y dependencias
  ansible.builtin.package:
    name: "{{ ruby_packages[ansible_distribution] }}"
    state: present
  become: true

- name: Verificar si tmuxinator ya está instalado
  ansible.builtin.command: which tmuxinator
  register: tmuxinator_check
  changed_when: false
  failed_when: false
  check_mode: false

- name: Instalar tmuxinator con gem
  ansible.builtin.gem:
    name: tmuxinator
    state: present
    user_install: true
  become: false
  when: tmuxinator_check.rc != 0
