---
# - name: Get real user home directory
#   command: echo $HOME
#   register: user_home
#   changed_when: false
#   become: no
#
- name: Ensure .config directory exists
  file:
    path: "{{ user_home }}/.config"
    state: directory
    mode: "0755"
  become: no

# stage config
- name: Find all directories in dotfiles/config
  find:
    paths: "{{ user_home }}/dotfiles/config"
    file_type: directory
    recurse: no
  register: config_directories
  become: no

- name: Create symbolic links for config directories
  file:
    src: "{{ item.path }}"
    dest: "{{ user_home }}/.config/{{ item.path | basename }}"
    state: link
    force: yes
  loop: "{{ config_directories.files }}"
  become: no

- name: Find all files in dotfiles/config
  find:
    paths: "{{ user_home }}/dotfiles/config"
    file_type: file
    recurse: no
  register: config_file
  become: no

- name: Create symbolic links for config directories
  file:
    src: "{{ item.path }}"
    dest: "{{ user_home }}/.config/{{ item.path | basename }}"
    state: link
    force: yes
  loop: "{{ config_file.files }}"
  become: no

# stage home
- name: Find all files in dotfiles/home
  find:
    paths: "{{ user_home }}/dotfiles/home"
    file_type: file
    recurse: no
    hidden: yes
  register: home_files
  become: no

- name: Create symbolic links for home files
  file:
    src: "{{ item.path }}"
    dest: "{{ user_home }}/{{ item.path | basename }}"
    state: link
    force: yes
  loop: "{{ home_files.files }}"
  become: no

- name: Find all directory in dotfiles/home/local/share
  find:
    paths: "{{ user_home }}/dotfiles/home/local/share"
    file_type: directory
    recurse: no
    hidden: yes
  register: home_directory
  become: no

- name: Create symbolic links for home files
  file:
    src: "{{ item.path }}"
    dest: "{{ user_home }}/.local/share/{{ item.path | basename }}"
    state: link
    force: yes
  loop: "{{ home_directory.files }}"
  become: no
