---
- name: Instalar dependencias extendidas (Fedora)
  ansible.builtin.dnf:
    name: "{{ extended_dependencies }}"
    state: present
    allowerasing: yes
    disable_gpg_check: yes
    install_weak_deps: no
  when: ansible_distribution == "Fedora"
  vars:
    extended_dependencies: "{{ package_managers.RedHat.dependencies.extended }}"
