---
- name: Actualiza el sistema
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when:
    - ansible_distribution == "Fedora"

- name: Instalar paquetes base
  ansible.builtin.dnf:
    name:
      - curl
      - git
    state: present
  when:
    - ansible_distribution == "Fedora"
