---
- name: Asegurar que los repositorios del sistema estén actualizados ({{ ansible_os_family }}:{{ ansible_distribution }})
  ansible.builtin.command: "{{ sentu_install.package_managers.fedora.update }}"
  become: true
  when:
    - ansible_distribution == "Fedora"
    - sentu_install.package_managers.fedora is defined
    - sentu_install.package_managers.fedora.update is defined

- name: Instalar paquetes base
  ansible.builtin.package:
    name:
      - curl
      - git
    state: present
  when: ansible_os_family != "Windows"
