---
galaxy_info:
  author: Tu Nombre
  description: Rol de Ansible para instalar Docker con soporte para múltiples sistemas operativos.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - system
    - docker
