---
- name: Descargar e instalar rye usando el script oficial
  ansible.builtin.command: "curl -sSf {{ sentu_install.install_scripts.rye }} | bash"
  become: true
  register: rye_install_output
  changed_when: "'Rye installed successfully' not in rye_install_output.stdout"
