- name: Crear enlaces simbólicos para la carpeta config
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../config/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: link
  loop: "{{ lookup('fileglob', playbook_dir + '/../config/*', wantlist=True) | map('basename') | list }}"

- name: Crear enlaces simbólicos para la carpeta home
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../home/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
  loop: "{{ lookup('fileglob', playbook_dir + '/../home/*', wantlist=True) | map('basename') | list }}"
