package_managers:
  manager: pacman
  update:
    - sudo
    - pacman
    - "-Suy"
    - "--noconfirm"
  install:
    - sudo
    - pacman
    - "-Sy"
    - "--needed"
    - "--noconfirm"
  repo:
    base:
      - echo
      - "Archlinux no requiere repo adicionales a yay"
  dependencies:
    core:
      - git
      - curl
      - wget
      - gcc
      - make
      - unzip
      - zsh
      - go
      - cargo
      - python
      - ruby
      - unrar
      - p7zip
      - xdg-user-dirs
      - lsd
      - jdk-openjdk
      - flatpak
      - linux-headers
      - automake
      - perl
      - elfutils
      - fontconfig
      - btop
    extended:
      - lazygit
      - ripgrep
      - fd
      - neovim
      - fastfetch
      - util-linux
      - cron
      - zoxide
      - python-neovim
      - kitty
      - lua
      - luarocks
      - docker
      - containerd
      - docker-compose
      - bat
      - fzf
      - httpie
      - tmux
      - tmuxinator
      - htop
      - lm_sensors
      - discord
      - alacritty
      - kdeconnect
      - kdenlive
      - openshot
      - vlc
      - mpv
      - soundconverter
      - audacity
      - muse
      - lmms
      - flowblade
      - xine-lib
      - libdvdread
      - libdvdnav
      - lsdvd
      - libdvbpsi
      - ffmpeg
      - libmatroska
      - xvidcore
      - gimp
      - inkscape
      - libreoffice-fresh
      - libreoffice-fresh-es
      - gstreamer
      - gst-plugins-base
      - gst-plugins-good
      - gst-plugins-bad
      - virt-manager
      - qemu
      - zeal
      - asciiquarium
      - bpytop
      - obsidian
      - mission-center
      - musikcube
      - google-chrome
