package_managers:
  manager: apt-get
  update:
    - sudo
    - apt-get
    - update
    - "-y"
  install:
    - sudo
    - apt-get
    - install
    - "-y"
    - "--allowerasing"
  repo:
    rpmfusion-nonfree:
      - sudo
      - apt-get
      - install
      - "-y"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
    rpmfusion-free:
      - sudo
      - apt-get
      - install
      - "-y"
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
    google-chrome:
      - sudo
      - gdebi
      - "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    lazygit:
      - sudo
      - apt-get
      - copr
      - enable
      - "atim/lazygit"
      - "-y"
  dependencies:
    core:
      - git
      - curl
      - wget
      - gcc
      - make
      - unzip
      - zsh
      - golang
      - cargo
      - g++
      - python3
      - ruby
      - unrar
      - p7zip
      - p7zip-plugins
      - xdg-user-dirs
      - lsd
      - java
      - apt-get-utils
      - flatpak
      - kernel-devel
      - gcc
      - make
      - automake
      - perl
      - elfutils-libelf-devel
    extended:
      - lazygit
      - ripgrep
      - fd-find
      - neovim
      - fastfetch
      - util-linux-user
      - anacron
      - zoxide
      - python3-neovim
      - kitty
      - lua-devel
      - luarocks
      - docker-cli
      - containerd
      - docker-compose
      - docker-switch
      - bat
      - fzf
      - httpie
      - ripgrep
      - tmux
      - htop
      - proselint
      - lm_sensors
      - discord
      - alacritty
      - kde-connect
      - apt-get-utils
      - kdenlive
      - openshot
      - vlc
      - mpv
      - soundconverter
      - audacity
      - muse
      - lmms
      - amarok
      - flowblade
      - xine-lib
      - xine-lib-extras
      - xine-lib-extras-freeworld
      - libdvdread
      - libdvdnav
      - lsdvd
      - libdvbpsi
      - ffmpeg
      - libmatroska
      - xvidcore
      - gimp
      - inkscape
      - libreoffice-writer
      - libreoffice-calc
      - libreoffice-impress
      - libreoffice-draw
      - libreoffice-langpack-es
      - gstreamer1-devel
      - gstreamer1-plugins-base-tools
      - gstreamer1-doc
      - gstreamer1-plugins-base-devel
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-devel
      - virt-manager
      - qemu
      - zeal
      - asciiquarium
      - bpytop
