sentu_install:
  package_managers:
    fedora:
      manager: dnf
      update:
        - sudo
        - dnf
        - update
        - "-y"
      install:
        - sudo
        - dnf
        - install
        - "-y"
        - "--allowerasing"
      repo:
        rpmfusion-nonfree:
          - sudo
          - dnf
          - install
          - "-y"
          - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
        rpmfusion-free:
          - sudo
          - dnf
          - install
          - "-y"
          - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
        docker:
          - sudo
          - dnf
          - config-manager
          - addrepo
          - "--from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo"
        google-chrome:
          - sudo
          - dnf
          - install
          - "-y"
          - "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
        lazygit:
          - sudo
          - dnf
          - copr
          - enable
          - "atim/lazygit"
          - "-y"
      dependencies:
        core:
          - git
          - curl
          - wget
          - gcc
          - make
          - unzip
          - zsh
          - golang
          - cargo
          - g++
          - python3
          - ruby
          - unrar
          - p7zip
          - p7zip-plugins
          - xdg-user-dirs
          - lsd
          - java
          - dnf-utils
          - flatpak
          - kernel-devel
          - gcc
          - make
          - automake
          - perl
          - elfutils-libelf-devel
        extended:
          - lazygit
          - ripgrep
          - fd-find
          - neovim
          - fastfetch
          - util-linux-user
          - anacron
          - neovim
          - python3-neovim
          - kitty
          - lua-devel
          - luarocks
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - bat
          - fzf
          - httpie
          - ripgrep
          - tmux
          - htop
          - proselint
          - lm_sensors
          - discord
          - alacritty
          - kde-connect
          - dnf-utils
          - kdenlive
          - openshot
          - vlc
          - mpv
          - gnome-mpv
          - soundconverter
          - audacity
          - muse
          - lmms
          - amarok
          - flowblade
          - dnf-plugins-core
          - xine-lib
          - xine-lib-extras
          - xine-lib-extras-freeworld
          - libdvdread
          - libdvdnav
          - lsdvd
          - libdvbpsi
          - ffmpeg
          - libmatroska
          - xvidcore
          - gimp
          - inkscape
          - libreoffice-writer
          - libreoffice-calc
          - libreoffice-impress
          - libreoffice-draw
          - libreoffice-langpack-es
          - gstreamer1-devel
          - gstreamer1-plugins-base-tools
          - gstreamer1-doc
          - gstreamer1-plugins-base-devel
          - gstreamer1-plugins-good
          - gstreamer1-plugins-good-extras
          - gstreamer1-plugins-bad-free
          - gstreamer1-plugins-bad-free-devel
  install_scripts:
    uv: "https://astral.sh/uv/install.sh"
    rye: "https://rye.astral.sh/get"
  install_post_install_commands:
    - command: "go install oss.terrastruct.com/d2@latest"
      description: "Instalando d2 diagram"
    - command: "curl -fsS https://dl.brave.com/install.sh | sh"
      description: "Instalando Brave"
    - command: "git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm"
      description: "Configurando tmux plugin manager"
    - command: "tmux source ~/.tmux.conf"
      description: "Activando tmux"
    - command: "gem install tmuxinator"
      description: "Instalando tmuxinator"
    - command: "flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo"
      description: "Actualizando repo Flatpak"
    - command: "flatpak install flathub md.obsidian.Obsidian"
      description: "Instalando Obsidian"
    - command: "sudo usermod -aG docker $USER"
      description: "Añadiendo el usuario al grupo docker (puede requerir reiniciar sesión)"
phase_1:
  steps:
    - task: update_system
    - task: install_dependencies
      group: core
    - task: install_and_configure_zsh
    - task: install_uv
    - task: install_rye
    - task: install_uv # Duplicado, lo corregiremos
phase_2:
  steps:
    - task: install_dependencies
      group: extended
    - task: install_fonts
    - task: configurar_docker
    - task: install_post_install
    - task: install_dotfiles
