- name: Ejecutar comandos post-instalación
  ansible.builtin.shell: "{{ item.command }}"
  become: no
  loop: "{{ install_post_install_commands }}"
  when:
    - install_post_install_commands is defined
    - item.command is defined
  loop_control:
    loop_var: item
