---
- name: Añadir repositorio {{ repo_item.key }} ({{ ansible_distribution }})
  ansible.builtin.shell:
    argv: "{{ repo_item.value | format(fedora_version=fedora_version) }}"
  become: true
  when:
    - ansible_distribution == "Fedora"
    - package_managers is defined
    - package_managers.repo is defined
    - repo_item.value is defined
  loop: "{{ package_managers.repo | dict2items }}"
  loop_control:
    loop_var: repo_item

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
