---
- name: Establecer la versión de Fedora como un hecho (fact)
  ansible.builtin.set_fact:
    fedora_version: "{{ ansible_distribution_major_version }}"
  when: ansible_distribution == "Fedora"

- name: Añadir repositorio {{ repo_item.key }} ({{ ansible_distribution }})
  ansible.builtin.shell:
    argv: "{{ repo_item.value | format(fedora_version=fedora_version) }}"
  become: true
  when:
    - ansible_distribution == "Fedora"
    - sentu_install.package_managers.fedora is defined
    - sentu_install.package_managers.fedora.repo is defined
    - repo_item.value is defined
  loop: "{{ sentu_install.package_managers.fedora.repo | dict2items }}"
  loop_control:
    loop_var: repo_item
