---
- name: Añadir repositorio {{ repo_item.key }} ({{ ansible_distribution }})
  ansible.builtin.shell:
    argv: "{{ repo_item.value | format(fedora_version=fedora_version) }}"
  become: true
  ignore_errors: true
  when:
    - ansible_distribution == "Fedora"
    - package_managers is defined
    - package_managers.repo is defined
    - repo_item.value is defined
  loop: "{{ package_managers.repo | dict2items }}"
  loop_control:
    loop_var: repo_item
