---
- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  ignore_errors: true

- name: Crear grupo docker (si no existe)
  ansible.builtin.group:
    name: docker
    state: present
  become: true

# - name: Obtener el usuario actual
#   become: false
#   ansible.builtin.set_fact:
#     current_user: "{{ ansible_user_id }}"

- name: Añadir el usuario actual al grupo docker
  ansible.builtin.user:
    name: "{{ current_user }}"
    groups: docker
    append: true
    state: present
  become: true
  when: docker_add_current_user | bool

- name: Añadir usuarios adicionales al grupo docker
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
    state: present
  with_items: "{{ docker_additional_users }}"
  become: true
  when: docker_additional_users | length > 0

# - name: Configurar Docker para iniciar en el arranque
#   ansible.builtin.systemd:
#     name: docker
#     enabled: "{{ docker_start_on_boot }}"
#     state: started
#   become: true
#   when: docker_start_on_boot

- name: Configurar Docker para iniciar en el arranque
  become: true
  when: docker_start_on_boot
  ansible.builtin.systemd_service:
    name: docker.service
    enabled: true
    masked: no
