---
- name: Verificar si Docker ya está instalado
  ansible.builtin.command: which docker
  register: docker_check
  changed_when: false
  failed_when: false

- name: Instalar paquetes prerequisitos para Docker en Fedora
  ansible.builtin.package:
    name:
      - dnf-plugins-core
    state: present
  become: true
  when: docker_check.rc != 0

- name: Añadir el repositorio de Docker a Fedora
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $releasever
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/fedora/gpg
    enabled: yes
  become: true
  when: docker_check.rc != 0

- name: Instalar Docker CE, CLI y containerd.io en Fedora
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true
  when: docker_check.rc != 0
  notify: restart docker
  vars:
    update_cache: yes
