---
- name: Instalar dependencias core
  block:
    - name: Instalar dependencias core (Fedora)
      ansible.builtin.dnf:
        name: "{{ core_dependencies }}"
        state: present
      # vars:
      #   core_dependencies: "{{ package_managers.RedHat.dependencies.core | default([]) }}"
      when: ansible_distribution == "Fedora"

    - name: Instalar dependencias core (Debian/Ubuntu)
      ansible.builtin.apt:
        name: "{{ core_dependencies }}"
        state: present
        update_cache: true
      vars:
        core_dependencies: "{{ package_managers.debian.dependencies.core | default([]) }}"
      when: ansible_os_family == "Debian"

    - name: Instalar dependencias core (Red Hat/CentOS)
      ansible.builtin.yum:
        name: "{{ core_dependencies }}"
        state: present
      vars:
        core_dependencies: "{{ package_managers.redhat.dependencies.core | default([]) }}"
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"

    - name: Install package from AUR using a Pacman compatible AUR helper
      community.general.pacman:
        name: "{{ core_dependencies }}"
        state: present
        executable: yay
        extra_args: --builddir /var/cache/yay
      # vars:
      #   core_dependencies: "{{ package_managers.dependencies.core | default([]) }}"
      when: ansible_os_family == "Archlinux"

    - name: Instalar dependencias core (openSUSE)
      community.general.zypper:
        name: "{{ core_dependencies }}"
        state: present
        update_cache: true
      vars:
        core_dependencies: "{{ package_managers.dependencies.core | default([]) }}"
      when: ansible_distribution == "openSUSE Leap" or ansible_distribution == "openSUSE Tumbleweed"

    - name: Mostrar mensaje si la distribuci칩n no est치 soportada para dependencias core
      ansible.builtin.debug:
        msg: "Distribuci칩n {{ ansible_distribution }} no soportada para la instalaci칩n de dependencias core."
      when:
        - ansible_distribution != "Fedora"
        - ansible_os_family != "Debian"
        - ansible_os_family != "RedHat"
        - ansible_distribution != "openSUSE Leap"
        - ansible_distribution != "openSUSE Tumbleweed"
  become: true
