- name: Instalar dependencias core (Fedora)
  ansible.builtin.package:
    name: "{{ core_dependencies }}"
    state: present
  when: ansible_distribution == "Fedora"
  vars:
    core_dependencies: "{{ sentu_install.package_managers.fedora.dependencies.core }}"
# Ejemplo para otras distribuciones (Debian/Ubuntu)
#- name: Instalar dependencias core (Debian/Ubuntu)
#  ansible.builtin.apt:
#    name: "{{ core_dependencies }}"
#    state: present
#    update_cache: yes
#  when: ansible_os_family == "Debian"
#  vars:
#    core_dependencies:
#      - curl
#      - git
#      # ... (otras dependencias core para Debian/Ubuntu)
