---
- name: Configuración Inicial del Sistema y Dotfiles
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  roles:
    - role: test
    - role: 00_load_vars
    - role: 01_base_system_configuration
    - role: 02_add_repositories
    - role: 03_install_core_dependencies
    - role: 04_install_uv
    - role: 05_install_nvm
    - role: 06_install_lazygit
      when: selected_packages is not defined or 'lazygit' in selected_packages
    - role: 07_install_extended_dependencies
      when: >-
        selected_packages is not defined
        or selected_packages | length > 0
        or (selected_cask_packages is defined and selected_cask_packages | length > 0)
    - role: 08_install_docker
      when: >-
        selected_packages is not defined
        or 'docker' in selected_packages
        or 'docker-cli' in selected_packages
        or 'docker-compose' in selected_packages
        or 'containerd' in selected_packages
    - role: 09_post_install
      when: >-
        selected_packages is not defined
        or selected_packages | length > 0
        or (selected_cask_packages is defined and selected_cask_packages | length > 0)
    - role: 10_config_zsh
    - role: 11_install_flatpak
    - role: 12_install_fonts
    - role: 13_install_wallpapers
    - role: 14_dotfiles_management
