---
- name: Configuración Inicial del Sistema y Dotfiles
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars_files:
    - vars/installer_config.yaml

  roles:
    - role: test
    - role: 00_load_vars
    - role: 01_base_system_configuration
    - role: 02_add_repositories
    - role: 03_install_core_dependencies
    - role: 04_install_uv
    - role: 05_install_nvm
    - role: 06_install_lazygit
    - role: 07_install_extended_dependencies
    - role: 08_install_docker
    - role: 09_post_install
    - role: 10_config_zsh
    - role: 11_install_flatpak
    - role: 12_install_fonts
    # - role: 13_install_wallpapers
    - role: 14_dotfiles_management
