---
- name: Configuración Inicial del Sistema y Dotfiles
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars_files:
    - vars/installer_config.yaml

  roles:
    - role: test
    - role: base_system_configuration
    - role: add_repositories
    - role: install_core_dependencies
    - role: install_uv
    - role: install_rye
    - role: install_nvm
    - role: install_extended_dependencies
    - role: install_post_install
    - role: config_zsh
    - role: install_flatpak
    - role: install_fonts
    - role: dotfiles_management
    # ... (añadiremos más roles aquí)
