---
- name: Instalar dependencias para Brave
  ansible.builtin.package:
    name: "{{ brave_dependencies[ansible_distribution] }}"
    state: present
  become: true

- name: Instalar Brave en Debian/Ubuntu
  when: ansible_os_family == "Debian"
  block:
    - name: A침adir clave GPG de Brave
      ansible.builtin.apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        state: present
      become: true

    - name: A침adir repositorio de Brave
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
        state: present
        filename: brave-browser
      become: true

    - name: Instalar Brave Browser
      ansible.builtin.apt:
        name: brave-browser
        state: present
        update_cache: true
      become: true

- name: Instalar Brave en CentOS/RHEL/Fedora
  when: ansible_os_family == "RedHat"
  block:
    - name: A침adir repositorio de Brave
      ansible.builtin.get_url:
        url: https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
        dest: /etc/yum.repos.d/brave-browser.repo
        mode: "0644"
      become: true

    - name: Instalar Brave Browser
      ansible.builtin.package:
        name: brave-browser
        state: present
      become: true

- name: Instalar Brave en Arch Linux usando yay
  when: ansible_distribution == "Archlinux"
  block:
    - name: Verificar si yay est치 instalado
      ansible.builtin.command: which yay
      register: yay_check
      changed_when: false
      failed_when: false
      check_mode: false

    - name: Instalar Brave con yay
      when: yay_check.rc == 0
      ansible.builtin.command: yay -S --noconfirm brave-bin
      become: false
